name: Build and push

on:
  push:
    branches:
      - master
  create:
    tags:
      - '*'

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install kubebuilder
        run: |
          os=$(go env GOOS)
          arch=$(go env GOARCH)

          # download kubebuilder and extract it to tmp
          curl -L https://go.kubebuilder.io/dl/3.3.0/${os}/${arch} | tar -xz -C /tmp/

          # move to a long-term location and put it on your path
          sudo mv /tmp/kubebuilder_3.3.0_${os}_${arch} /usr/local/kubebuilder
          export PATH=$PATH:/usr/local/kubebuilder/bin
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: make docker-build
      - name: Push
        run: make docker-push

